apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-demo

resources:
  - namespace.yaml
  - details-api.yaml
  - internal-api.yaml
  - mcp-server.yaml
  - secret-lockdown.yaml